<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHECKOUT (179.99)</name>
   <tag></tag>
   <elementGuidId>07ad51c6-2f33-40af-85d1-333d202cada3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkOutButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkOutButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d873e8c-ee63-43c1-b7d5-4172556a19de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f2a9744-4acb-47b0-97b5-1482ec6ec661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium tami uft-class ng-binding</value>
      <webElementGuid>c7ffaca9-abd8-4616-96fc-a466a16d13db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>checkout()</value>
      <webElementGuid>985ca7f7-c92c-4346-b81a-c2658eba77f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkOutButton</value>
      <webElementGuid>b3cb727e-4a63-4f61-87e5-4c1da803b698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_out_btn</value>
      <webElementGuid>97c84f74-1363-4a68-acd5-3ce669d3fc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT ($179.99)</value>
      <webElementGuid>0d1dbd93-c9ed-4859-910f-405ba34d1e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkOutButton&quot;)</value>
      <webElementGuid>4c3eb42f-1996-42d4-a58f-4c2341869cde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkOutButton']</value>
      <webElementGuid>ab0d4d14-e3ac-407a-b25f-07813f6adbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shoppingCart']/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>7e7f6f6c-e613-4fd4-9315-746d6368ded0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>2c7949ed-8d29-46ee-ae87-018b8818975e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'checkOutButton' and @name = 'check_out_btn' and (text() = 'CHECKOUT ($179.99)' or . = 'CHECKOUT ($179.99)')]</value>
      <webElementGuid>0670a2fd-b3ec-434d-8fa6-2c712bf83790</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
