<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Shop Now</name>
   <tag></tag>
   <elementGuidId>0377cbf5-8781-41b0-8381-cfd74c85f0dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;headphonesImg&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headphonesLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fc9efb71-fbc7-4b67-9c31-868571cb4194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headphonesLink</value>
      <webElementGuid>ab7b15c8-f7e4-4d2e-9125-295f02e67cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_nowSub roboto-regular ng-scope</value>
      <webElementGuid>46a8ea5a-ac67-4ca5-99d8-b49627b1605a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Shop_Now</value>
      <webElementGuid>4c43075e-270f-4158-9a20-1ef0d763d53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop Now</value>
      <webElementGuid>1db0f096-e772-4019-984b-1dbb2d22b279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headphonesLink&quot;)</value>
      <webElementGuid>9a31b02c-91f2-4057-bd87-a0a80eb61165</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='headphonesLink']</value>
      <webElementGuid>c0bb2c6a-cf16-4c93-a50c-f4f2caf4af28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headphonesImg']/div/label</value>
      <webElementGuid>a0f1d76e-f449-4bf2-9940-aaaa82182885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label</value>
      <webElementGuid>1e2dd102-6f2a-49ac-ad72-cf1f615a8b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'headphonesLink' and (text() = 'Shop Now' or . = 'Shop Now')]</value>
      <webElementGuid>9e282098-75bc-418c-a717-907528562979</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
